# Generated by Django 4.2.7 on 2026-02-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FaceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                ("original_filename", models.CharField(max_length=255)),
                ("encoding", models.TextField()),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Face Image",
                "verbose_name_plural": "Face Images",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
